Demo.Pl/Models/EmployeeViewModel.cs
using Demo.DAL.Entities;
using Microsoft.AspNetCore.Http;
using System;
using System.ComponentModel.DataAnnotations;

namespace Demo.Pl.Models
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        [MaxLength(50, ErrorMessage = "Maximum Length of name is 50 chars")]
        [MinLength(5, ErrorMessage = "Minimum Lengtth of Name is 5 chars")]
        public string Name { get; set; }
        [Range(22, 60, ErrorMessage = "Age must be between 22 and 60")]
        public int? Age { get; set; }
        [RegularExpression(@"^[0-9]{1,10}-[a-zA-Z]{1,40}-[a-zA-Z]{1,40}-[a-zA-Z]{1,40}$",
            ErrorMessage = "Address must be like '123-Street-Region-City'")]
        public string Address { get; set; }
        [DataType(DataType.Currency)]
        [Range(4000, 8000, ErrorMessage = "Salary Must Be between 4000 and 8000")]
        public decimal Salary { get; set; }
        public bool IsActive { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        [DataType(DataType.PhoneNumber)]
        public string PhoneNumber { get; set; }

        public DateTime HireDate { get; set; }

        public int DepartmentId { get; set; }
        public virtual Department Department { get; set; }

        public IFormFile Image { get; set; }

        public string ImageName { get; set; }
    }
}

Demo.Pl/Controllers/DepartmentController.cs
using Demo.BLL.Interfaces;
using Demo.DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;

namespace Demo.Pl.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        private readonly IDepartmentRepository departmentRepository;

        public DepartmentController(IDepartmentRepository departmentRepository)
        {
            this.departmentRepository = departmentRepository;
        }
        public IActionResult Index()
        {
            //One Way Binding
            //1- ViewData is A dictionary object (intoduction in asp.net framework 3.5)
            // => It helps us to transfer the data from controller to view
            ViewData["Message"] = "Hello View Data";


            //2- viewBag is a Dynamic Property (introduction in asp.net framework 4.0 based on dynamic feature)
            // => It helps us to transfer the data from controller to view
              ViewBag.Message = "Hello View Bag";

            //3- TempData is A dictionary object (intoduction in asp.net framework 3.5)
            // is used to pass data between two consecutive requests
            //only works during the current and subsequent request
            

            return View(departmentRepository.GetAll());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Department department)
        {
            if (ModelState.IsValid) // Server Side Validation
            {
                departmentRepository.Add(department);
                TempData["Message"] = "Department is Created Successfully";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(department);
            }
        }

        public IActionResult Details(int? id , string ViewName= "Details")
        {
            if (id == null)
                return NotFound();
            var Department = departmentRepository.Get(id);
            if (Department == null)
                return NotFound();
            return View(ViewName , Department);
        }

       public IActionResult Edit(int? id)
        {
            //    if (id == null)
            //        return NotFound();
            //    var Department = departmentRepository.Get(id);
            //    if (Department == null)
            //        return NotFound();
            //    return View(Department);
            return Details(id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([FromRoute] int? id ,Department department)
        {
            if(id != department.Id)
                return BadRequest();
            if(ModelState.IsValid) //server side validation
            {
                try
                {
                    departmentRepository.Update(department);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {
                    
                    return View(department);
                }
            }
            return View(department);
        }

        public IActionResult Delete(int? id)
        {
            return Details(id, "Delete");
        }
        [HttpPost]
        public IActionResult Delete([FromRoute] int? id, Department department)
        {
            if (id != department.Id)
                return BadRequest();
            try
            {
                departmentRepository.Delete(department);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(department);
            }
        }
    }
}

Demo.Pl/Controllers/EmployeeController.cs
using AutoMapper;
using Demo.BLL.Interfaces;
using Demo.BLL.Repositories;
using Demo.DAL.Entities;
using Demo.Pl.Helpers;
using Demo.Pl.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Demo.Pl.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        //private readonly IEmployeeRepository employeeRepository;
        //private readonly IDepartmentRepository departmentRepository;
        private readonly IMapper mapper;

        public IUnitofWork UnitofWork { get; }

        // public EmployeeController(IEmployeeRepository employeeRepository, IDepartmentRepository departmentRepository ,IMapper mapper)
        public EmployeeController(IUnitofWork unitofWork ,IMapper mapper)
        {
            UnitofWork = unitofWork;
            //this.employeeRepository = employeeRepository;
            //this.departmentRepository = departmentRepository;
            this.mapper = mapper;
        }

        public async Task<IActionResult>  Index(string SearchValue)
        {
            if (string.IsNullOrEmpty(SearchValue))
            { 
                var MappedEmps = mapper.Map<IEnumerable<Employee> , IEnumerable<EmployeeViewModel>>(await UnitofWork.EmployeeRepository.GetAll());
                return  View(MappedEmps);

            }
            else
            {
                
                var MappedEmps = mapper.Map<IEnumerable<Employee>, IEnumerable<EmployeeViewModel>>(await UnitofWork.EmployeeRepository.SearchEmployee(SearchValue));

                return View(MappedEmps);
            }
           
        }
        public IActionResult Create()
        {
            ViewBag.Departments = UnitofWork.DepartmentRepository.GetAll();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(EmployeeViewModel employee)
        {
            if (ModelState.IsValid) // Server Side Validation
            {
                //var MappedEmp = new Employee() //Manual Mapping
                //{
                //    Id = employee.Id,
                //    Name = employee.Name,
                //    Address = employee.Address,
                //    Age = employee.Age,
                //    DepartmentId = employee.DepartmentId,
                //    Email = employee.Email,
                //    HireDate = employee.HireDate,
                //    IsActive = employee.IsActive,
                //    PhoneNumber = employee.PhoneNumber,
                //    Salary = employee.Salary

                //};
               employee.ImageName = DocumentSettings.UploadFile(employee.Image, "Imags");
                var MappedEmp =  mapper.Map<EmployeeViewModel ,Employee >(employee);
                // employeeRepository.Add(employee); 
                 await UnitofWork.EmployeeRepository.Add(MappedEmp);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewBag.Departments = UnitofWork.DepartmentRepository.GetAll();
                return View(employee);
            }
        }

        public async Task<IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id == null)
                return NotFound();
            var employee =await UnitofWork.EmployeeRepository.Get(id);
           
            if (employee == null)
                return NotFound();

            var MappedEmp = mapper.Map<Employee,  EmployeeViewModel > (employee);
            return View(ViewName, MappedEmp);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            //    if (id == null)
            //        return NotFound();
            //    var Department = employeeRepository.Get(id);
            //    if (Department == null)
            //        return NotFound();
            //    return View(Department);
            ViewBag.Departments =await UnitofWork.DepartmentRepository.GetAll();
            return await Details(id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int? id, EmployeeViewModel employee)
        {
            if (id != employee.Id)
                return BadRequest();
            if (ModelState.IsValid) //server side validation
            {
                try
                {
                    var MappedEmp = mapper.Map<EmployeeViewModel, Employee>(employee);
                    await UnitofWork.EmployeeRepository.Update(MappedEmp);
                    return RedirectToAction(nameof(Index));
                }
                catch
                {

                    return View(employee);
                }
            }
            ViewBag.Departments = UnitofWork.DepartmentRepository.GetAll();
            return View(employee);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            return await Details(id, "Delete");
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromRoute] int? id, EmployeeViewModel employee)
        {
            if (id != employee.Id)
                return BadRequest();
            try
            {
                var MappedEmp = mapper.Map<EmployeeViewModel, Employee>(employee);
                DocumentSettings.Delete(employee.ImageName, "Imags");
                await UnitofWork.EmployeeRepository.Delete(MappedEmp);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(employee);
            }
        }
    }
}

Demo.Pl/Views/Employee/Create.cshtml
@*@model Employee*@
@model EmployeeViewModel
@{
    ViewData["Title"] = "Create";
}

<h1>Create New Employee</h1>

<br />
<br />

<form asp-action="Create" enctype="multipart/form-data" >
      @*  <div asp-validation-summary="All"></div>
        <div class="form-group">
        <label class="col-form-label" asp-for="Name"></label>
        <input  class="form-control" asp-for="Name"/>
        <span asp-validation-for="Name" class="text"></span>
        </div>
        <div class="form-group">
        <label class="col-form-label" asp-for="Address"></label>
        <input  class="form-control" asp-for="Address"/>
        <span asp-validation-for="Address" class="text"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Age"></label>
        <input  class="form-control" asp-for="Age"/>
        <span asp-validation-for="Age" class="text"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Salary"></label>
        <input  class="form-control" asp-for="Salary"/>
        <span asp-validation-for="Salary" class="text"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Email"></label>
        <input  class="form-control" asp-for="Email"/>
        <span asp-validation-for="Email" class="text"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="PhoneNumber"></label>
        <input  class="form-control" asp-for="PhoneNumber"/>
        <span asp-validation-for="PhoneNumber" class="text"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="IsActive"></label>
        <input  class="form-control" asp-for="IsActive"/>
        <span asp-validation-for="IsActive" class="text"></span>
        </div>*@
         <partial name="CreateEditEmployee"></partial>
         <input  type="submit"  class="btn btn-primary" value="Submit"/> |
         <a asp-action="Index"   class="btn btn-warning"> Back To List</a>
</form>
@section ScriptSection{
  @*  <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>*@
    <partial name="_ValidationScriptsPartial"></partial>
}

Demo.Pl/Views/Employee/CreateEditEmployee.cshtml
@using Demo.BLL.Interfaces
@*@model Employee*@
@inject IUnitofWork unitOfWork
@model EmployeeViewModel
@inject IDepartmentRepository departmentRepository
@{
   //var Departments = new SelectList(ViewBag.Departments, "Id", "Name");
    var Departments = new SelectList(await unitOfWork.DepartmentRepository.GetAll(), "Id", "Name");
}
  <div asp-validation-summary="All"></div>
        <div class="form-group">
        <label class="col-form-label" asp-for="Name"></label>
        <input  class="form-control" asp-for="Name"/>
        <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="form-group">
        <label class="col-form-label" asp-for="Address"></label>
        <input  class="form-control" asp-for="Address"/>
        <span asp-validation-for="Address" class="text-danger"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Age"></label>
        <input  class="form-control" asp-for="Age"/>
        <span asp-validation-for="Age" class="text-danger"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Salary"></label>
        <input  class="form-control" asp-for="Salary"/>
        <span asp-validation-for="Salary" class="text-danger"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Email"></label>
        <input  class="form-control" asp-for="Email"/>
        <span asp-validation-for="Email" class="text-danger"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="PhoneNumber"></label>
        <input  class="form-control" asp-for="PhoneNumber"/>
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div> 
        
        <div class="form-group">
        <label class="col-form-label" asp-for="DepartmentId"></label>
        <select asp-for="DepartmentId" asp-items="Departments">
            <option>-- Select Department--</option>
        </select>
        <span asp-validation-for="DepartmentId" class="text-danger"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="IsActive"></label>
        <input  class="form-control" asp-for="IsActive"/>
        <span asp-validation-for="IsActive" class="text-danger"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Image"></label>
        <input  class="form-control" asp-for="Image"/>
        <span asp-validation-for="Image" class="text-danger"></span>
        </div>
         <div class="form-group">
        <label class="col-form-label" asp-for="HireDate"></label>
        <input  class="form-control" asp-for="HireDate"/>
        <span asp-validation-for="HireDate" class="text-danger"></span>
        </div>

Demo.Pl/Views/Employee/Delete.cshtml
@*@model Employee*@
@model EmployeeViewModel
@{
    ViewData["Title"] = "Delete";
}

<h1>Are You Sure To Delete This Employee?</h1>

<br />
<br />

<form asp-action="Delete" asp-controller="Employee">
         <input hidden asp-for="Id" />
       @* <div class="form-group">
        <label class="col-form-label" asp-for="Name"></label>
        <input  class="form-control" asp-for="Name" readonly/>
        
        </div>
        <div class="form-group">
        <label class="col-form-label" asp-for="Address"></label>
        <input  class="form-control" asp-for="Address" readonly/>
       
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Age"></label>
        <input  class="form-control" asp-for="Age" readonly/>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Salary"></label>
        <input  class="form-control" asp-for="Salary" readonly/>
       
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Email"></label>
        <input  class="form-control" asp-for="Email" readonly/>
     
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="PhoneNumber"></label>
        <input  class="form-control" asp-for="PhoneNumber" readonly/>
        
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="IsActive"></label>
        <input  class="form-control" asp-for="IsActive" readonly/>
   
        </div>*@
        <partial name="DeleteDetailsEmployee"></partial>
      <input  type="submit"  class="btn btn-primary" value="Submit"/> |
      <a asp-action="Index" asp-controller="Department"  class="btn btn-warning"> Back To List</a>
</form>

Demo.Pl/Views/Employee/DeleteDetailsEmployee.cshtml
@*@model Employee*@
@model EmployeeViewModel
        <div class="form-group">
        <label class="col-form-label" asp-for="Name"></label>
        <input  class="form-control" asp-for="Name" readonly/>
        
        </div>
        <div class="form-group">
        <label class="col-form-label" asp-for="Address"></label>
        <input  class="form-control" asp-for="Address" readonly/>
       
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Age"></label>
        <input  class="form-control" asp-for="Age" readonly/>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Salary"></label>
        <input  class="form-control" asp-for="Salary" readonly/>
       
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Email"></label>
        <input  class="form-control" asp-for="Email" readonly/>
     
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="PhoneNumber"></label>
        <input  class="form-control" asp-for="PhoneNumber" readonly/>
        
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="IsActive"></label>
        <input  class="form-control" disabled asp-for="IsActive" readonly/>
   
        </div>

Demo.Pl/Views/Employee/Details.cshtml
@*@model Employee*@
@model EmployeeViewModel
@{
    ViewData["Title"] = "Details";
}

<h1>Employee Details</h1>

<div>
   @* 
    <div class="form-group">
       <label asp-for="Name" class="col-form-label"></label>
       <input class="form-control" asp-for="Name" readonly />
    </div>  
    <div class="form-group">
       <label asp-for="Address" class="col-form-label"></label>
       <input class="form-control" asp-for="Address" readonly />
    </div>  
    <div class="form-group">
       <label asp-for="Age" class="col-form-label"></label>
       <input class="form-control" asp-for="Age" readonly />
    </div> 
    <div class="form-group">
       <label asp-for="Email" class="col-form-label"></label>
       <input class="form-control" asp-for="Email" readonly />
    </div> 
    <div class="form-group">
       <label asp-for="PhoneNumber" class="col-form-label"></label>
       <input class="form-control" asp-for="PhoneNumber" readonly />
    </div>  
    <div class="form-group">
       <label asp-for="Salary" class="col-form-label"></label>
       <input class="form-control" asp-for="Salary" readonly />
    </div> 
    <div class="form-group">
       <label asp-for="IsActive" class="col-form-label"></label>
       <input class="form-control" disabled asp-for="IsActive"  />
    </div>*@
      <partial name="DeleteDetailsEmployee"></partial>
    <div>
        <a asp-action="Edit" asp-route-id="Id" class="btn btn-primary">Edit</a> |
        <a asp-action="Index" class="btn btn-secondary">Back To List</a>
    </div>
</div>

Demo.Pl/Views/Employee/Edit.cshtml
@model EmployeeViewModel
@*@model Employee*@
@{
    ViewData["Title"] = "Update";
}

<h1>Update New Employee</h1>

<br />
<br />

<form asp-action="Edit" asp-controller="Employee">
        <input hidden asp-for="Id" />
 @*       <div class="form-group">
        <label class="col-form-label" asp-for="Name"></label>
        <input  class="form-control" asp-for="Name"/>
        <span asp-validation-for="Name" class="text"></span>
        </div>
        <div class="form-group">
        <label class="col-form-label" asp-for="Address"></label>
        <input  class="form-control" asp-for="Address"/>
        <span asp-validation-for="Address" class="text"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Age"></label>
        <input  class="form-control" asp-for="Age"/>
        <span asp-validation-for="Age" class="text"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Salary"></label>
        <input  class="form-control" asp-for="Salary"/>
        <span asp-validation-for="Salary" class="text"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="Email"></label>
        <input  class="form-control" asp-for="Email"/>
        <span asp-validation-for="Email" class="text"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="PhoneNumber"></label>
        <input  class="form-control" asp-for="PhoneNumber"/>
        <span asp-validation-for="PhoneNumber" class="text"></span>
        </div> 
        <div class="form-group">
        <label class="col-form-label" asp-for="IsActive"></label>
        <input  class="form-control" asp-for="IsActive"/>
        <span asp-validation-for="IsActive" class="alert-danger"></span>
        </div>*@
       <partial name="CreateEditEmployee"></partial>
       <input  type="submit"  class="btn btn-primary" value="Save"/> |
       <a asp-action="Index" asp-controller="Employee"  class="btn btn-warning"> Back To List</a>
</form>
@section ScriptSection{
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Demo.Pl/Views/Employee/Index.cshtml
@*@model IEnumerable<Employee>*@
@model IEnumerable<EmployeeViewModel>
@{
    ViewData["Title"] = "Index";
}


 <h1>All Employees</h1>
 <br />
 <br />

 <a asp-action="Create" asp-controller="Employee" class="btn btn-primary"> Create New Department</a>

 <br />
 <br />

 <form class="my-3" asp-action="Index">
     <div class="row">
         <div class="col-sm-8">
             <input  placeholder="Search By Name" name="SearchValue" class="form-control"/>
         </div>
          <div class="col-sm-4">
             <input type="submit" value="Search" class="btn btn-success btn-block"/>
         </div>
     </div>

 </form>









 @if(Model.Count() > 0)
 {
     <table class="table table-striped table-hover">
         <thead>
            
             <th>@Html.DisplayNameFor(D => D.Name)</th> 
             <th>@Html.DisplayNameFor(D => D.Address)</th> 
             <th>@Html.DisplayNameFor(D => D.Image)</th> 
             <th>@Html.DisplayNameFor(D => D.Age)</th> 
             <th>@Html.DisplayNameFor(D => D.Salary)</th> 
             <th>@Html.DisplayNameFor(D => D.Email)</th> 
             <th>@Html.DisplayNameFor(D => D.PhoneNumber)</th> 
             <th>@Html.DisplayNameFor(D => D.Department)</th> 
             <th>@Html.DisplayNameFor(D => D.IsActive)</th> 
             <th>@Html.DisplayNameFor(D => D.HireDate)</th> 
             <th>Details</th> 
             <th>Update</th> 
             <th>Delete</th>
         </thead>
         <tbody>
             @foreach (var employee in Model)
            {
                <tr>
                 
                    <td>@employee.Name</td>
                    <td>@employee.Address</td> 
                    <td>
                        <img src="~/files/Imags/@employee.ImageName" class="img-circle" width="40" height="40" alt="Employee-image">
                    </td>
                    <td>@employee.Age</td>
                   @*<td>@employee.Salary</td> *@
                    <td>@Html.DisplayFor(m=>@employee.Salary)</td>
                   @*<td>@employee.Email</td>*@
                     <td>@Html.DisplayFor(m=>@employee.Email)</td>

                    <td>@employee.PhoneNumber</td> 
                     <td>@employee.Department?.Name</td> 
                    @*<td>@employee.IsActive</td>*@

                    <td>@Html.DisplayFor(m=>@employee.IsActive)</td>
                    <td>@employee.HireDate</td>   
              @*      <td>
                        <a asp-action="Details" asp-controller="Employee" asp-route-id="@employee.Id" class="btn btn-success"> <i class="fas fa-eye"></i> Details</a>
                    </td>  
                    <td>
                        <a asp-action="Edit" asp-controller="Employee" asp-route-id="@employee.Id" class="btn btn-warning"> <i class="fas fa-edit"></i> Update</a>
                    </td> 
                    <td>
                        <a asp-action="Delete" asp-controller="Employee" asp-route-id="@employee.Id" class="btn btn-danger"> <i class="fas fa-trash"></i> Delete</a>
                    </td>*@
                    <partial name="_ButtonsPartialView" model="@employee.Id"></partial>

                </tr>
            }
         </tbody>

     </table>
 }  else{
     <div class="alert alert-danger">
         <p> There is No Employee</p>
     </div>
 }